config/routes.rb
Rails.application.routes.draw do
  get 'reader/index'

  get 'upload/index'

  resources :companies
  resources :txt_files
  get 'home/index'

  root 'home#index'

end

app/models/txt_file.rb
class TxtFile
	include Mongoid::Document
	field :id, type: Integer
	field :name, type: String
	field :path, type: String
end

app/controllers/txt_files_controller.rb
class TxtFilesController < ApplicationController
  before_action :set_txt_file, only: [:show, :edit, :update, :destroy]
  # GET /txt_files
  # GET /txt_files.json
  def index
    @txt_files = TxtFile.all
  end

  # GET /txt_files/1
  # GET /txt_files/1.json
  def show
  end

  # GET /txt_files/new
  def new
    @txt_file = TxtFile.new
  end

  # GET /txt_files/1/edit
  def edit
  end

  # POST /txt_files
  # POST /txt_files.json
  def create
    # Capturing the object file
    uploaded_io = params[:txt_file][:file]
    # writing the file to disk
    File.open(Rails.root.join('uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end

    # adding the filename and path to database
    filename = uploaded_io.original_filename
    path = Rails.root.join('uploads', uploaded_io.original_filename)
    @txt_file = TxtFile.new(:name => filename, :path => path)

    respond_to do |format|
      if @txt_file.save
        format.html { redirect_to companies_path, notice: '' }
        format.json { render :show, status: :created, location: @txt_file }

        # push all links in the database
        require "#{Rails.root}/app/fileReader.rb"
        reader = FileReader.new
        reader.readFile(@txt_file.path.to_s)
        
      else
        format.html { render :new }
        format.json { render json: @txt_file.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @txt_file.update(txt_file_params)
        format.html { redirect_to @txt_file, notice: 'Txt file was successfully updated.' }
        format.json { render :show, status: :ok, location: @txt_file }
      else
        format.html { render :edit }
        format.json { render json: @txt_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /txt_files/1
  # DELETE /txt_files/1.json
  def destroy
    #File.delete(@txt_file.path)
    @txt_file.destroy
    respond_to do |format|
      format.html { redirect_to txt_files_url, notice: 'Txt file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_txt_file
    @txt_file = TxtFile.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def txt_file_params
    params.require(:txt_file).permit(:file)
  end

end

app/helpers/txt_files_helper.rb
module TxtFilesHelper
end

app/views/txt_files/_form.html.erb
<%= form_for(@txt_file) do |f| %>
  <% if @txt_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@txt_file.errors.count, "error") %> prohibited this txt_file from being saved:</h2>

      <ul>
      <% @txt_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :file %>
  </div>

  <div class="actions">
    <%= f.submit"Upload" %>
  </div>
<% end %>

app/views/txt_files/edit.html.erb
<h1>Editing Txt File</h1>

<%= render 'form' %>

<%= link_to 'Show', @txt_file %> |
<%= link_to 'Back', txt_files_path %>

app/views/txt_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Txt Files</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @txt_files.each do |txt_file| %>
      <tr>
        <td><%= txt_file.name %></td>
        <td><%= txt_file.path %></td>
        <td><%= link_to 'Show', txt_file %></td>
        <td><%= link_to 'Edit', edit_txt_file_path(txt_file) %></td>
        <td><%= link_to 'Destroy', txt_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Txt file', new_txt_file_path %>
<%= link_to 'Back', home_index_path %>

app/views/txt_files/new.html.erb
<br /><big><h1>New Txt File</h1>

<%= render 'form' %>
<br /><br />
&emsp;&emsp;<%= link_to 'Back', home_index_path %>
</big>

app/views/txt_files/show.html.erb
<p id="notice">
	<%= notice %>

</p>


	Website URLs are extracted successfully and pushed into the database.
<br />
	A Job has been scheduled in the background to update the database with live data from Facebook.
	<br />

	Please make sure you type: bundle exec sidekiq in the Terminal window if you have not done so for this session


<p>
	<strong>Name:</strong>
	<%= @txt_file.name %>
</p>

<p>
	<strong>Path:</strong>
	<%= @txt_file.path %>
</p>

<%= link_to 'Edit', edit_txt_file_path(@txt_file) %> |
<%= link_to 'Back', txt_files_path %>